version: "3.7"

services:
  app:
    build: ./app
    # restart: always
    volumes:
      - ./app:/app
    env_file:
      - .env/development/app
      - .env/development/database
    ports:
      - "80:8000"
    # expose:
    #   - 3000

  # nginx:
  #   build: ./nginx
  #   restart: always
  #   ports:
  #     - "80:80"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #
  # database:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   env_file:
  #     - .env/development/database
    # volumes:
    #   - db_data:/path

# volumes:
#   db_data:
